ci:
  skip: [go-test-repo-mod]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
    -   id: remove-crlf
-   repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
    -   id: go-fmt
    -   id: go-imports
-   repo: https://github.com/TekWizely/pre-commit-golang
    rev: v0.8.2
    hooks:
    -   id: go-test-repo-mod
