FROM golang:latest

RUN go get golang.org/x/tools/gopls
RUN go get github.com/uudashr/gopkgs/v2/cmd/gopkgs
RUN go get github.com/ramya-rao-a/go-outline
RUN go get github.com/go-delve/delve/cmd/dlv
RUN go get honnef.co/go/tools/cmd/staticcheck
