FROM golang:latest

RUN go get -v golang.org/x/tools/gopls
RUN go get -v github.com/uudashr/gopkgs/v2/cmd/gopkgs
RUN go get -v github.com/ramya-rao-a/go-outline
RUN go get -v github.com/go-delve/delve/cmd/dlv
RUN go get -v honnef.co/go/tools/cmd/staticcheck
